export interface CostRow {
  label: string;
  range: string;
  raw: number; // midpoint — used for proportional bar widths
  category: 'rent' | 'food' | 'transport' | 'utilities' | 'internet' | 'healthcare' | 'entertainment';
}

export interface CountryCostData {
  note: string;       // e.g. "Estimates for a single person in Lisbon"
  totalRange: string; // e.g. "$1,500–$2,200"
  rows: CostRow[];
}

// All amounts are approximate USD equivalents for a single expat/nomad lifestyle.
export const COUNTRY_COST_DATA: Record<string, CountryCostData> = {
  portugal: {
    note: 'Single person, Lisbon — USD equivalent',
    totalRange: '$1,500–$2,200',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$1,000–$1,600', raw: 1300, category: 'rent' },
      { label: 'Food & Groceries', range: '$280–$380', raw: 330, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$50–$80', raw: 65, category: 'transport' },
      { label: 'Utilities (electricity, water)', range: '$80–$130', raw: 105, category: 'utilities' },
      { label: 'Internet (fibre)', range: '$25–$40', raw: 33, category: 'internet' },
      { label: 'Healthcare (private insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$100–$200', raw: 150, category: 'entertainment' },
    ],
  },
  spain: {
    note: 'Single person, Madrid — USD equivalent',
    totalRange: '$1,400–$2,200',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$900–$1,500', raw: 1200, category: 'rent' },
      { label: 'Food & Groceries', range: '$270–$370', raw: 320, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$50–$80', raw: 65, category: 'transport' },
      { label: 'Utilities', range: '$80–$130', raw: 105, category: 'utilities' },
      { label: 'Internet (fibre)', range: '$25–$40', raw: 33, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$100–$200', raw: 150, category: 'entertainment' },
    ],
  },
  uae: {
    note: 'Single person, Dubai — USD equivalent',
    totalRange: '$2,500–$4,500',
    rows: [
      { label: 'Rent (1-bed, expat area)', range: '$1,500–$2,800', raw: 2150, category: 'rent' },
      { label: 'Food & Groceries', range: '$400–$600', raw: 500, category: 'food' },
      { label: 'Transport (car/taxi)', range: '$150–$300', raw: 225, category: 'transport' },
      { label: 'Utilities', range: '$150–$250', raw: 200, category: 'utilities' },
      { label: 'Internet', range: '$60–$100', raw: 80, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$100–$200', raw: 150, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$200–$400', raw: 300, category: 'entertainment' },
    ],
  },
  canada: {
    note: 'Single person, Toronto — CAD/USD approximate',
    totalRange: '$2,500–$3,800',
    rows: [
      { label: 'Rent (1-bed, city)', range: '$1,400–$2,200', raw: 1800, category: 'rent' },
      { label: 'Food & Groceries', range: '$400–$550', raw: 475, category: 'food' },
      { label: 'Transport (transit pass)', range: '$100–$180', raw: 140, category: 'transport' },
      { label: 'Utilities', range: '$120–$180', raw: 150, category: 'utilities' },
      { label: 'Internet', range: '$50–$80', raw: 65, category: 'internet' },
      { label: 'Healthcare (supplemental)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$200–$350', raw: 275, category: 'entertainment' },
    ],
  },
  germany: {
    note: 'Single person, Berlin — USD equivalent',
    totalRange: '$1,800–$3,000',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$1,000–$1,800', raw: 1400, category: 'rent' },
      { label: 'Food & Groceries', range: '$300–$450', raw: 375, category: 'food' },
      { label: 'Transport (Deutschlandticket)', range: '$50–$60', raw: 55, category: 'transport' },
      { label: 'Utilities', range: '$100–$160', raw: 130, category: 'utilities' },
      { label: 'Internet', range: '$30–$50', raw: 40, category: 'internet' },
      { label: 'Healthcare (public/private)', range: '$150–$250', raw: 200, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$150–$280', raw: 215, category: 'entertainment' },
    ],
  },
  netherlands: {
    note: 'Single person, Amsterdam — USD equivalent',
    totalRange: '$2,200–$3,500',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$1,300–$2,200', raw: 1750, category: 'rent' },
      { label: 'Food & Groceries', range: '$330–$480', raw: 405, category: 'food' },
      { label: 'Transport (OV-chipkaart)', range: '$80–$130', raw: 105, category: 'transport' },
      { label: 'Utilities', range: '$100–$180', raw: 140, category: 'utilities' },
      { label: 'Internet', range: '$35–$55', raw: 45, category: 'internet' },
      { label: 'Healthcare (mandatory insurance)', range: '$150–$250', raw: 200, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$180–$320', raw: 250, category: 'entertainment' },
    ],
  },
  georgia: {
    note: 'Single person, Tbilisi — USD equivalent',
    totalRange: '$700–$1,400',
    rows: [
      { label: 'Rent (1-bed, central)', range: '$300–$700', raw: 500, category: 'rent' },
      { label: 'Food & Groceries', range: '$150–$250', raw: 200, category: 'food' },
      { label: 'Transport (metro/bus)', range: '$30–$60', raw: 45, category: 'transport' },
      { label: 'Utilities', range: '$50–$100', raw: 75, category: 'utilities' },
      { label: 'Internet (fibre)', range: '$10–$20', raw: 15, category: 'internet' },
      { label: 'Healthcare (private insurance)', range: '$30–$60', raw: 45, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$70–$150', raw: 110, category: 'entertainment' },
    ],
  },
  thailand: {
    note: 'Single person, Bangkok — USD equivalent',
    totalRange: '$800–$1,600',
    rows: [
      { label: 'Rent (1-bed, expat area)', range: '$350–$800', raw: 575, category: 'rent' },
      { label: 'Food & Groceries', range: '$170–$300', raw: 235, category: 'food' },
      { label: 'Transport (BTS + Grab)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$50–$90', raw: 70, category: 'utilities' },
      { label: 'Internet (fibre)', range: '$15–$30', raw: 23, category: 'internet' },
      { label: 'Healthcare (private insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$80–$200', raw: 140, category: 'entertainment' },
    ],
  },
  mexico: {
    note: 'Single person, Mexico City — USD equivalent',
    totalRange: '$1,000–$1,800',
    rows: [
      { label: 'Rent (1-bed, Condesa/Roma)', range: '$500–$1,000', raw: 750, category: 'rent' },
      { label: 'Food & Groceries', range: '$200–$320', raw: 260, category: 'food' },
      { label: 'Transport (Metro + Uber)', range: '$50–$90', raw: 70, category: 'transport' },
      { label: 'Utilities', range: '$60–$100', raw: 80, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$100–$200', raw: 150, category: 'entertainment' },
    ],
  },
  colombia: {
    note: 'Single person, Medellín — USD equivalent',
    totalRange: '$900–$1,600',
    rows: [
      { label: 'Rent (1-bed, El Poblado)', range: '$400–$900', raw: 650, category: 'rent' },
      { label: 'Food & Groceries', range: '$180–$300', raw: 240, category: 'food' },
      { label: 'Transport (Metro + Uber)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$60–$100', raw: 80, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$80–$180', raw: 130, category: 'entertainment' },
    ],
  },
  estonia: {
    note: 'Single person, Tallinn — USD equivalent',
    totalRange: '$1,500–$2,200',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$700–$1,300', raw: 1000, category: 'rent' },
      { label: 'Food & Groceries', range: '$280–$380', raw: 330, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$50–$80', raw: 65, category: 'transport' },
      { label: 'Utilities', range: '$100–$170', raw: 135, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$120–$220', raw: 170, category: 'entertainment' },
    ],
  },
  japan: {
    note: 'Single person, Tokyo — USD equivalent',
    totalRange: '$1,400–$2,200',
    rows: [
      { label: 'Rent (1-bed, central Tokyo)', range: '$700–$1,400', raw: 1050, category: 'rent' },
      { label: 'Food & Groceries', range: '$300–$430', raw: 365, category: 'food' },
      { label: 'Transport (Suica/commuter)', range: '$80–$150', raw: 115, category: 'transport' },
      { label: 'Utilities', range: '$80–$140', raw: 110, category: 'utilities' },
      { label: 'Internet', range: '$25–$45', raw: 35, category: 'internet' },
      { label: 'Healthcare (NHI)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$150–$250', raw: 200, category: 'entertainment' },
    ],
  },
  australia: {
    note: 'Single person, Sydney — AUD/USD approximate',
    totalRange: '$2,500–$3,800',
    rows: [
      { label: 'Rent (1-bed, inner city)', range: '$1,400–$2,200', raw: 1800, category: 'rent' },
      { label: 'Food & Groceries', range: '$400–$580', raw: 490, category: 'food' },
      { label: 'Transport (Opal card)', range: '$100–$180', raw: 140, category: 'transport' },
      { label: 'Utilities', range: '$120–$200', raw: 160, category: 'utilities' },
      { label: 'Internet', range: '$50–$80', raw: 65, category: 'internet' },
      { label: 'Healthcare (extras cover)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$200–$350', raw: 275, category: 'entertainment' },
    ],
  },
  brazil: {
    note: 'Single person, São Paulo — USD equivalent',
    totalRange: '$1,100–$1,900',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$500–$1,000', raw: 750, category: 'rent' },
      { label: 'Food & Groceries', range: '$220–$360', raw: 290, category: 'food' },
      { label: 'Transport (metro + Uber)', range: '$50–$90', raw: 70, category: 'transport' },
      { label: 'Utilities', range: '$70–$120', raw: 95, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (private plan)', range: '$60–$120', raw: 90, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$100–$200', raw: 150, category: 'entertainment' },
    ],
  },
  singapore: {
    note: 'Single person, Singapore — USD equivalent',
    totalRange: '$3,000–$5,000',
    rows: [
      { label: 'Rent (1-bed, central)', range: '$2,000–$3,500', raw: 2750, category: 'rent' },
      { label: 'Food & Groceries', range: '$400–$600', raw: 500, category: 'food' },
      { label: 'Transport (EZ-Link card)', range: '$100–$180', raw: 140, category: 'transport' },
      { label: 'Utilities', range: '$120–$200', raw: 160, category: 'utilities' },
      { label: 'Internet', range: '$40–$70', raw: 55, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$100–$200', raw: 150, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$200–$400', raw: 300, category: 'entertainment' },
    ],
  },
  'south-africa': {
    note: 'Single person, Cape Town — USD equivalent',
    totalRange: '$1,200–$2,000',
    rows: [
      { label: 'Rent (1-bed, city bowl)', range: '$550–$1,100', raw: 825, category: 'rent' },
      { label: 'Food & Groceries', range: '$250–$380', raw: 315, category: 'food' },
      { label: 'Transport (Uber + car)', range: '$70–$130', raw: 100, category: 'transport' },
      { label: 'Utilities', range: '$80–$140', raw: 110, category: 'utilities' },
      { label: 'Internet', range: '$25–$45', raw: 35, category: 'internet' },
      { label: 'Healthcare (medical aid)', range: '$80–$160', raw: 120, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$120–$220', raw: 170, category: 'entertainment' },
    ],
  },
  malaysia: {
    note: 'Single person, Kuala Lumpur — USD equivalent',
    totalRange: '$900–$1,600',
    rows: [
      { label: 'Rent (1-bed, KLCC area)', range: '$400–$900', raw: 650, category: 'rent' },
      { label: 'Food & Groceries', range: '$180–$300', raw: 240, category: 'food' },
      { label: 'Transport (Grab + LRT)', range: '$50–$90', raw: 70, category: 'transport' },
      { label: 'Utilities', range: '$60–$100', raw: 80, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$80–$160', raw: 120, category: 'entertainment' },
    ],
  },
  poland: {
    note: 'Single person, Warsaw — USD equivalent',
    totalRange: '$1,200–$2,000',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$600–$1,200', raw: 900, category: 'rent' },
      { label: 'Food & Groceries', range: '$240–$370', raw: 305, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$40–$70', raw: 55, category: 'transport' },
      { label: 'Utilities', range: '$90–$150', raw: 120, category: 'utilities' },
      { label: 'Internet', range: '$15–$30', raw: 23, category: 'internet' },
      { label: 'Healthcare (private)', range: '$60–$120', raw: 90, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$100–$200', raw: 150, category: 'entertainment' },
    ],
  },
  'costa-rica': {
    note: 'Single person, San José — USD equivalent',
    totalRange: '$1,400–$2,200',
    rows: [
      { label: 'Rent (1-bed, central)', range: '$650–$1,200', raw: 925, category: 'rent' },
      { label: 'Food & Groceries', range: '$280–$400', raw: 340, category: 'food' },
      { label: 'Transport (bus + Uber)', range: '$60–$100', raw: 80, category: 'transport' },
      { label: 'Utilities', range: '$80–$130', raw: 105, category: 'utilities' },
      { label: 'Internet', range: '$30–$50', raw: 40, category: 'internet' },
      { label: 'Healthcare (CAJA + private)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$120–$220', raw: 170, category: 'entertainment' },
    ],
  },
  'new-zealand': {
    note: 'Single person, Auckland — NZD/USD approximate',
    totalRange: '$2,200–$3,300',
    rows: [
      { label: 'Rent (1-bed, city)', range: '$1,300–$2,000', raw: 1650, category: 'rent' },
      { label: 'Food & Groceries', range: '$380–$530', raw: 455, category: 'food' },
      { label: 'Transport (AT Hop card)', range: '$100–$170', raw: 135, category: 'transport' },
      { label: 'Utilities', range: '$100–$170', raw: 135, category: 'utilities' },
      { label: 'Internet', range: '$50–$80', raw: 65, category: 'internet' },
      { label: 'Healthcare (supplemental)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$180–$300', raw: 240, category: 'entertainment' },
    ],
  },
  italy: {
    note: 'Single person, Milan — USD equivalent',
    totalRange: '$1,500–$2,500',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$800–$1,500', raw: 1150, category: 'rent' },
      { label: 'Food & Groceries', range: '$320–$460', raw: 390, category: 'food' },
      { label: 'Transport (ATM pass)', range: '$60–$100', raw: 80, category: 'transport' },
      { label: 'Utilities', range: '$100–$170', raw: 135, category: 'utilities' },
      { label: 'Internet', range: '$25–$40', raw: 33, category: 'internet' },
      { label: 'Healthcare (SSN + top-up)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$150–$270', raw: 210, category: 'entertainment' },
    ],
  },
  france: {
    note: 'Single person, Paris — USD equivalent',
    totalRange: '$1,800–$3,000',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$1,000–$1,800', raw: 1400, category: 'rent' },
      { label: 'Food & Groceries', range: '$350–$500', raw: 425, category: 'food' },
      { label: 'Transport (Navigo pass)', range: '$70–$120', raw: 95, category: 'transport' },
      { label: 'Utilities', range: '$100–$170', raw: 135, category: 'utilities' },
      { label: 'Internet', range: '$25–$45', raw: 35, category: 'internet' },
      { label: 'Healthcare (SS + mutuelle)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$150–$280', raw: 215, category: 'entertainment' },
    ],
  },
  turkey: {
    note: 'Single person, Istanbul — USD equivalent',
    totalRange: '$800–$1,500',
    rows: [
      { label: 'Rent (1-bed, central)', range: '$350–$800', raw: 575, category: 'rent' },
      { label: 'Food & Groceries', range: '$180–$300', raw: 240, category: 'food' },
      { label: 'Transport (Istanbulkart)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$60–$110', raw: 85, category: 'utilities' },
      { label: 'Internet', range: '$15–$30', raw: 23, category: 'internet' },
      { label: 'Healthcare (SGK + private)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$80–$160', raw: 120, category: 'entertainment' },
    ],
  },
  indonesia: {
    note: 'Single person, Bali/Jakarta — USD equivalent',
    totalRange: '$900–$1,600',
    rows: [
      { label: 'Rent (1-bed villa/apartment)', range: '$350–$800', raw: 575, category: 'rent' },
      { label: 'Food & Groceries', range: '$180–$320', raw: 250, category: 'food' },
      { label: 'Transport (scooter + Grab)', range: '$60–$120', raw: 90, category: 'transport' },
      { label: 'Utilities', range: '$60–$100', raw: 80, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$80–$160', raw: 120, category: 'entertainment' },
    ],
  },
  vietnam: {
    note: 'Single person, Ho Chi Minh City — USD equivalent',
    totalRange: '$700–$1,300',
    rows: [
      { label: 'Rent (1-bed, District 2/3)', range: '$280–$700', raw: 490, category: 'rent' },
      { label: 'Food & Groceries', range: '$150–$260', raw: 205, category: 'food' },
      { label: 'Transport (Grab + bus)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$50–$90', raw: 70, category: 'utilities' },
      { label: 'Internet', range: '$10–$20', raw: 15, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$40–$80', raw: 60, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$60–$140', raw: 100, category: 'entertainment' },
    ],
  },
  india: {
    note: 'Single person, Bangalore/Mumbai — USD equivalent',
    totalRange: '$600–$1,200',
    rows: [
      { label: 'Rent (1-bed, good area)', range: '$250–$600', raw: 425, category: 'rent' },
      { label: 'Food & Groceries', range: '$130–$240', raw: 185, category: 'food' },
      { label: 'Transport (auto + Ola)', range: '$30–$70', raw: 50, category: 'transport' },
      { label: 'Utilities', range: '$40–$80', raw: 60, category: 'utilities' },
      { label: 'Internet', range: '$5–$15', raw: 10, category: 'internet' },
      { label: 'Healthcare (insurance)', range: '$30–$70', raw: 50, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$50–$120', raw: 85, category: 'entertainment' },
    ],
  },
  argentina: {
    note: 'Single person, Buenos Aires — USD equivalent',
    totalRange: '$900–$1,600',
    rows: [
      { label: 'Rent (1-bed, Palermo)', range: '$400–$900', raw: 650, category: 'rent' },
      { label: 'Food & Groceries', range: '$180–$300', raw: 240, category: 'food' },
      { label: 'Transport (SUBE card)', range: '$30–$70', raw: 50, category: 'transport' },
      { label: 'Utilities', range: '$60–$110', raw: 85, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (prepaga)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$80–$160', raw: 120, category: 'entertainment' },
    ],
  },
  chile: {
    note: 'Single person, Santiago — USD equivalent',
    totalRange: '$1,300–$2,100',
    rows: [
      { label: 'Rent (1-bed, Providencia)', range: '$650–$1,200', raw: 925, category: 'rent' },
      { label: 'Food & Groceries', range: '$260–$380', raw: 320, category: 'food' },
      { label: 'Transport (Bip! card)', range: '$60–$100', raw: 80, category: 'transport' },
      { label: 'Utilities', range: '$80–$130', raw: 105, category: 'utilities' },
      { label: 'Internet', range: '$25–$40', raw: 33, category: 'internet' },
      { label: 'Healthcare (isapre)', range: '$70–$140', raw: 105, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$100–$200', raw: 150, category: 'entertainment' },
    ],
  },
  greece: {
    note: 'Single person, Athens — USD equivalent',
    totalRange: '$1,100–$1,900',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$500–$1,000', raw: 750, category: 'rent' },
      { label: 'Food & Groceries', range: '$240–$360', raw: 300, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$50–$80', raw: 65, category: 'transport' },
      { label: 'Utilities', range: '$80–$140', raw: 110, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (EOPYY + private)', range: '$60–$120', raw: 90, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$100–$200', raw: 150, category: 'entertainment' },
    ],
  },
  'czech-republic': {
    note: 'Single person, Prague — USD equivalent',
    totalRange: '$1,300–$2,100',
    rows: [
      { label: 'Rent (1-bed, Prague 1/2)', range: '$700–$1,300', raw: 1000, category: 'rent' },
      { label: 'Food & Groceries', range: '$260–$380', raw: 320, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$40–$70', raw: 55, category: 'transport' },
      { label: 'Utilities', range: '$90–$150', raw: 120, category: 'utilities' },
      { label: 'Internet', range: '$15–$30', raw: 23, category: 'internet' },
      { label: 'Healthcare (public + top-up)', range: '$70–$140', raw: 105, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$100–$200', raw: 150, category: 'entertainment' },
    ],
  },
  croatia: {
    note: 'Single person, Zagreb/Split — USD equivalent',
    totalRange: '$1,100–$1,900',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$550–$1,100', raw: 825, category: 'rent' },
      { label: 'Food & Groceries', range: '$230–$350', raw: 290, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$80–$140', raw: 110, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (HZZ + private)', range: '$60–$120', raw: 90, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$100–$180', raw: 140, category: 'entertainment' },
    ],
  },
  serbia: {
    note: 'Single person, Belgrade — USD equivalent',
    totalRange: '$900–$1,500',
    rows: [
      { label: 'Rent (1-bed, central)', range: '$400–$900', raw: 650, category: 'rent' },
      { label: 'Food & Groceries', range: '$200–$320', raw: 260, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$30–$60', raw: 45, category: 'transport' },
      { label: 'Utilities', range: '$70–$120', raw: 95, category: 'utilities' },
      { label: 'Internet', range: '$15–$25', raw: 20, category: 'internet' },
      { label: 'Healthcare (private insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$80–$160', raw: 120, category: 'entertainment' },
    ],
  },
  romania: {
    note: 'Single person, Bucharest — USD equivalent',
    totalRange: '$900–$1,600',
    rows: [
      { label: 'Rent (1-bed, central)', range: '$400–$900', raw: 650, category: 'rent' },
      { label: 'Food & Groceries', range: '$200–$320', raw: 260, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$30–$60', raw: 45, category: 'transport' },
      { label: 'Utilities', range: '$70–$130', raw: 100, category: 'utilities' },
      { label: 'Internet (very fast!)', range: '$10–$20', raw: 15, category: 'internet' },
      { label: 'Healthcare (private clinic)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$80–$160', raw: 120, category: 'entertainment' },
    ],
  },
  bulgaria: {
    note: 'Single person, Sofia — USD equivalent',
    totalRange: '$800–$1,400',
    rows: [
      { label: 'Rent (1-bed, central Sofia)', range: '$350–$800', raw: 575, category: 'rent' },
      { label: 'Food & Groceries', range: '$180–$300', raw: 240, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$30–$60', raw: 45, category: 'transport' },
      { label: 'Utilities', range: '$70–$120', raw: 95, category: 'utilities' },
      { label: 'Internet', range: '$10–$20', raw: 15, category: 'internet' },
      { label: 'Healthcare (private)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$70–$140', raw: 105, category: 'entertainment' },
    ],
  },
  hungary: {
    note: 'Single person, Budapest — USD equivalent',
    totalRange: '$1,100–$1,800',
    rows: [
      { label: 'Rent (1-bed, city centre)', range: '$500–$1,000', raw: 750, category: 'rent' },
      { label: 'Food & Groceries', range: '$230–$360', raw: 295, category: 'food' },
      { label: 'Transport (monthly pass)', range: '$35–$65', raw: 50, category: 'transport' },
      { label: 'Utilities', range: '$80–$140', raw: 110, category: 'utilities' },
      { label: 'Internet', range: '$15–$25', raw: 20, category: 'internet' },
      { label: 'Healthcare (TB + private)', range: '$60–$120', raw: 90, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$90–$180', raw: 135, category: 'entertainment' },
    ],
  },
  ireland: {
    note: 'Single person, Dublin — EUR/USD approximate',
    totalRange: '$2,500–$3,800',
    rows: [
      { label: 'Rent (1-bed, Dublin city)', range: '$1,500–$2,400', raw: 1950, category: 'rent' },
      { label: 'Food & Groceries', range: '$400–$580', raw: 490, category: 'food' },
      { label: 'Transport (Leap card)', range: '$100–$180', raw: 140, category: 'transport' },
      { label: 'Utilities', range: '$130–$220', raw: 175, category: 'utilities' },
      { label: 'Internet', range: '$40–$65', raw: 53, category: 'internet' },
      { label: 'Healthcare (private plan)', range: '$100–$200', raw: 150, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$200–$350', raw: 275, category: 'entertainment' },
    ],
  },
  sweden: {
    note: 'Single person, Stockholm — SEK/USD approximate',
    totalRange: '$2,000–$3,200',
    rows: [
      { label: 'Rent (1-bed, central)', range: '$1,000–$1,900', raw: 1450, category: 'rent' },
      { label: 'Food & Groceries', range: '$380–$540', raw: 460, category: 'food' },
      { label: 'Transport (SL pass)', range: '$80–$140', raw: 110, category: 'transport' },
      { label: 'Utilities', range: '$100–$180', raw: 140, category: 'utilities' },
      { label: 'Internet', range: '$30–$55', raw: 43, category: 'internet' },
      { label: 'Healthcare (landsting + top-up)', range: '$80–$160', raw: 120, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$180–$300', raw: 240, category: 'entertainment' },
    ],
  },
  norway: {
    note: 'Single person, Oslo — NOK/USD approximate',
    totalRange: '$2,500–$4,000',
    rows: [
      { label: 'Rent (1-bed, central Oslo)', range: '$1,300–$2,200', raw: 1750, category: 'rent' },
      { label: 'Food & Groceries', range: '$450–$650', raw: 550, category: 'food' },
      { label: 'Transport (Ruter pass)', range: '$100–$170', raw: 135, category: 'transport' },
      { label: 'Utilities', range: '$120–$200', raw: 160, category: 'utilities' },
      { label: 'Internet', range: '$40–$70', raw: 55, category: 'internet' },
      { label: 'Healthcare (public + top-up)', range: '$80–$160', raw: 120, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$200–$380', raw: 290, category: 'entertainment' },
    ],
  },
  denmark: {
    note: 'Single person, Copenhagen — DKK/USD approximate',
    totalRange: '$2,300–$3,500',
    rows: [
      { label: 'Rent (1-bed, central CPH)', range: '$1,200–$2,000', raw: 1600, category: 'rent' },
      { label: 'Food & Groceries', range: '$420–$600', raw: 510, category: 'food' },
      { label: 'Transport (Rejsekort)', range: '$90–$160', raw: 125, category: 'transport' },
      { label: 'Utilities', range: '$110–$190', raw: 150, category: 'utilities' },
      { label: 'Internet', range: '$35–$60', raw: 48, category: 'internet' },
      { label: 'Healthcare (sundhedssikring)', range: '$80–$160', raw: 120, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$180–$330', raw: 255, category: 'entertainment' },
    ],
  },
  finland: {
    note: 'Single person, Helsinki — EUR/USD approximate',
    totalRange: '$2,000–$3,000',
    rows: [
      { label: 'Rent (1-bed, central Helsinki)', range: '$1,000–$1,800', raw: 1400, category: 'rent' },
      { label: 'Food & Groceries', range: '$370–$530', raw: 450, category: 'food' },
      { label: 'Transport (HSL pass)', range: '$70–$130', raw: 100, category: 'transport' },
      { label: 'Utilities', range: '$100–$180', raw: 140, category: 'utilities' },
      { label: 'Internet', range: '$25–$45', raw: 35, category: 'internet' },
      { label: 'Healthcare (Kela + private)', range: '$80–$160', raw: 120, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$160–$280', raw: 220, category: 'entertainment' },
    ],
  },
  philippines: {
    note: 'Single person, Manila/Cebu — USD equivalent',
    totalRange: '$700–$1,300',
    rows: [
      { label: 'Rent (1-bed, BGC/Makati)', range: '$300–$700', raw: 500, category: 'rent' },
      { label: 'Food & Groceries', range: '$150–$270', raw: 210, category: 'food' },
      { label: 'Transport (Grab + Jeepney)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$60–$110', raw: 85, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (HMO)', range: '$40–$80', raw: 60, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$70–$140', raw: 105, category: 'entertainment' },
    ],
  },
  cambodia: {
    note: 'Single person, Phnom Penh/Siem Reap — USD equivalent',
    totalRange: '$700–$1,200',
    rows: [
      { label: 'Rent (1-bed, city)', range: '$300–$650', raw: 475, category: 'rent' },
      { label: 'Food & Groceries', range: '$150–$260', raw: 205, category: 'food' },
      { label: 'Transport (tuk-tuk + Grab)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$50–$100', raw: 75, category: 'utilities' },
      { label: 'Internet', range: '$15–$30', raw: 23, category: 'internet' },
      { label: 'Healthcare (private clinic)', range: '$40–$80', raw: 60, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$60–$120', raw: 90, category: 'entertainment' },
    ],
  },
  'sri-lanka': {
    note: 'Single person, Colombo — USD equivalent',
    totalRange: '$700–$1,300',
    rows: [
      { label: 'Rent (1-bed, Colombo 3)', range: '$300–$650', raw: 475, category: 'rent' },
      { label: 'Food & Groceries', range: '$150–$260', raw: 205, category: 'food' },
      { label: 'Transport (PickMe + bus)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$50–$90', raw: 70, category: 'utilities' },
      { label: 'Internet', range: '$15–$30', raw: 23, category: 'internet' },
      { label: 'Healthcare (private hospital)', range: '$40–$80', raw: 60, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$60–$130', raw: 95, category: 'entertainment' },
    ],
  },
  nepal: {
    note: 'Single person, Kathmandu — USD equivalent',
    totalRange: '$500–$900',
    rows: [
      { label: 'Rent (1-bed, Thamel/Lazimpat)', range: '$200–$450', raw: 325, category: 'rent' },
      { label: 'Food & Groceries', range: '$120–$220', raw: 170, category: 'food' },
      { label: 'Transport (taxi + micro)', range: '$30–$60', raw: 45, category: 'transport' },
      { label: 'Utilities', range: '$40–$80', raw: 60, category: 'utilities' },
      { label: 'Internet', range: '$10–$20', raw: 15, category: 'internet' },
      { label: 'Healthcare (private clinic)', range: '$30–$60', raw: 45, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$40–$100', raw: 70, category: 'entertainment' },
    ],
  },
  morocco: {
    note: 'Single person, Marrakech/Casablanca — USD equivalent',
    totalRange: '$700–$1,300',
    rows: [
      { label: 'Rent (1-bed, medina/ville)', range: '$300–$700', raw: 500, category: 'rent' },
      { label: 'Food & Groceries', range: '$150–$270', raw: 210, category: 'food' },
      { label: 'Transport (petit taxi + Careem)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$50–$90', raw: 70, category: 'utilities' },
      { label: 'Internet', range: '$15–$30', raw: 23, category: 'internet' },
      { label: 'Healthcare (private clinic)', range: '$40–$80', raw: 60, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$60–$130', raw: 95, category: 'entertainment' },
    ],
  },
  panama: {
    note: 'Single person, Panama City — USD',
    totalRange: '$1,400–$2,200',
    rows: [
      { label: 'Rent (1-bed, Marbella/Casco)', range: '$700–$1,300', raw: 1000, category: 'rent' },
      { label: 'Food & Groceries', range: '$280–$400', raw: 340, category: 'food' },
      { label: 'Transport (Metro + Uber)', range: '$60–$100', raw: 80, category: 'transport' },
      { label: 'Utilities', range: '$90–$150', raw: 120, category: 'utilities' },
      { label: 'Internet', range: '$30–$55', raw: 43, category: 'internet' },
      { label: 'Healthcare (private insurance)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$120–$220', raw: 170, category: 'entertainment' },
    ],
  },
  uruguay: {
    note: 'Single person, Montevideo — USD equivalent',
    totalRange: '$1,400–$2,200',
    rows: [
      { label: 'Rent (1-bed, Pocitos/Centro)', range: '$700–$1,300', raw: 1000, category: 'rent' },
      { label: 'Food & Groceries', range: '$280–$400', raw: 340, category: 'food' },
      { label: 'Transport (STM card)', range: '$50–$90', raw: 70, category: 'transport' },
      { label: 'Utilities', range: '$90–$150', raw: 120, category: 'utilities' },
      { label: 'Internet', range: '$30–$55', raw: 43, category: 'internet' },
      { label: 'Healthcare (mutualista)', range: '$80–$150', raw: 115, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$120–$220', raw: 170, category: 'entertainment' },
    ],
  },
  ecuador: {
    note: 'Single person, Quito/Cuenca — USD',
    totalRange: '$800–$1,400',
    rows: [
      { label: 'Rent (1-bed, good area)', range: '$350–$800', raw: 575, category: 'rent' },
      { label: 'Food & Groceries', range: '$170–$290', raw: 230, category: 'food' },
      { label: 'Transport (bus + InDriver)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$60–$100', raw: 80, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (private insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$70–$150', raw: 110, category: 'entertainment' },
    ],
  },
  peru: {
    note: 'Single person, Lima/Cusco — USD equivalent',
    totalRange: '$800–$1,500',
    rows: [
      { label: 'Rent (1-bed, Miraflores)', range: '$350–$800', raw: 575, category: 'rent' },
      { label: 'Food & Groceries', range: '$170–$300', raw: 235, category: 'food' },
      { label: 'Transport (Metro + Uber)', range: '$40–$80', raw: 60, category: 'transport' },
      { label: 'Utilities', range: '$60–$100', raw: 80, category: 'utilities' },
      { label: 'Internet', range: '$20–$35', raw: 28, category: 'internet' },
      { label: 'Healthcare (private clinic)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$70–$150', raw: 110, category: 'entertainment' },
    ],
  },
  kenya: {
    note: 'Single person, Nairobi — USD equivalent',
    totalRange: '$800–$1,500',
    rows: [
      { label: 'Rent (1-bed, Westlands/Karen)', range: '$350–$800', raw: 575, category: 'rent' },
      { label: 'Food & Groceries', range: '$170–$300', raw: 235, category: 'food' },
      { label: 'Transport (Uber + matatu)', range: '$50–$90', raw: 70, category: 'transport' },
      { label: 'Utilities', range: '$60–$100', raw: 80, category: 'utilities' },
      { label: 'Internet', range: '$20–$40', raw: 30, category: 'internet' },
      { label: 'Healthcare (private insurance)', range: '$50–$100', raw: 75, category: 'healthcare' },
      { label: 'Entertainment & Dining Out', range: '$70–$150', raw: 110, category: 'entertainment' },
    ],
  },
};

export function getCountryCostData(country: string): CountryCostData | undefined {
  return COUNTRY_COST_DATA[country];
}
